[build-system]
  requires = ["setuptools>=68.0"]
  build-backend = "setuptools.build_meta"

[project]
  name = "UtilityLib"
  description = "Python Helper for Repetitive Tasks with File and Data Management"
  version = "2.18"
  authors = [
    { name="Vishal Kumar Sahu", email="mail@vishalkumarsahu.in" },
  ]
  readme = "README.md"
  license = {file = "LICENSE"}
  requires-python = ">=3.8, <3.12"
  classifiers = [
    'Operating System :: OS Independent',
    'Intended Audience :: Science/Research',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    "Operating System :: OS Independent",
  ]
  dependencies = [
    'xmltodict',
    'sqlalchemy',
    'psutil',
    'pandas',
    'seaborn',
    'tqdm',
    'toml',
    'openpyxl',
    'schedule',
    'humanize',
  ]

[project.urls]
  Homepage = "https://github.com/TheBiomics/UtilityLib"
  Issues = "https://github.com/TheBiomics/UtilityLib/issues"
